apistagram/config/routes.rb
Apistagram::Application.routes.draw do
  root :to => "iphotos#index"

  resources  :auths,
             :iphotos

  resources :users, :only => [:show]             

  match '/auth/:provider/callback'  => 'auths#create'
  match '/auth/failure'             => 'auths#failure'
  match '/auth/:provider/setup'     => 'auths#setup'
  match '/signin'                   => 'auths#new',      :as => :signin
  match '/signout'                  => 'auths#destroy',  :as => :signout
  match '/contact'                  => 'users#contact'
  match '/advertize'                => 'users#advertize'
  match '/report'                   => 'users#report'

  match '/contact'                  => 'users#contact',  :as => :contact, :via => :post
  match '/advertize'                => 'users#advertize',  :as => :advertize, :via => :post
  match '/report'                   => 'users#report',  :as => :report, :via => :post

  match '/users/:id/photos/:sort'   => 'users#show'
  match '/legal'   => 'users#legal', :as => :legal

  namespace :admin do
    resources :users, :only => [:index, :destroy]
    resources :iphotos
    root :to => "users#index"


    match "fetch_photos" => 'users#fetch_photos', :as => 'fetch_photos', :via => 'post'
    match "approve_photos" => 'iphotos#approve_photos', :as => 'approve_photos', :via => 'post'
  end

  match '/remove_all_photos/:id'  => 'users#remove_all_photos', :via => :delete, :as => 'remove_all_photos'
  match '/remove_user/:id'  => 'users#destroy', :via => :delete, :as => 'remove_user'
  match "cakesta/:category"         => 'iphotos#index'
  match "cakesta/:category/:sort"   => 'iphotos#index' 
  match "tattsta/:category"         => 'iphotos#index'
  match "tattsta/:category/:sort"   => 'iphotos#index'
  match "tatstagram/:category"         => 'iphotos#index'
  match "tatstagram/:category/:sort"   => 'iphotos#index'     
  match 'iphotos/:id/favorite'    => 'iphotos#favorite', :via => 'get', :as => 'favorite'
  match 'iphotos/:id/add_comment' => 'iphotos#add_comment', :via => :post, :as => 'add_comment'
  match 'iphotos/:id/remove_comment/:comment_id' => 'iphotos#remove_comment', :via => :delete, :as => 'remove_comment'
  match 'login'                   => 'auths#new', :as => 'login' 
  match '/:id' => 'iphotos#public_show'
end

apistagram/app/models/user.rb
require 'iinstagram'
class User < ActiveRecord::Base
  # mount_uploader :image, ImageUploader
  include IInstagram

  attr_accessible :uid,
                  :token,
                  :image, 
                  :provider,
                  :website,
                  :bio,
                  :remote_image_url

  validates :uid, :provider,
            :presence => true

  validates :uid,
            :uniqueness => true

  has_many :favorites
  has_many :favorite_photos, :through => :favorites, :source => :iphoto,
           :order => 'created_at desc'
  has_many :comments
  has_many :commented_photos, :through => :comments, :source => :iphoto,
                      :conditions => "comments.commentable_type = 'Iphoto'",
                      :order => 'created_at desc'

  before_create :set_admin_if_required                      

  def set_admin_if_required
    self.is_admin = true if self.name == 'apistagram' 
  end

  def self.authenticate(auth, cpartner)
    user        = self.where(:provider => auth['provider'], :uid => auth['uid']).first
    user        ||= self.new(:provider => auth['provider'], :uid => auth['uid'])
    user.token  = auth['credentials']['token']
    if auth['info']
      user.image      = auth['info']["image"]     || "" unless auth['info']["image"] == "http://images.instagram.com/profiles/anonymousUser.jpg"
      user.name       = auth['info']['nickname']  || ""
      user.full_name  = auth['info']['name']      || ""
      user.email      = auth['info']['email']     || ""
      user.website    = auth["info"]["website"]
      user.bio        = auth["info"]["bio"]
    end

    user.save!
    user
  end

  def get_grams
    cakesta_tags = Tag.where(:partner_id => 1)
    tattsta_tags = Tag.where(:partner_id => 2)

    cakesta_tags.each do |tag|
      50.times do |i|
        self.delay.fetch_grams(tag, tag.partner_id)
      end
    end

    tattsta_tags.each do |tag|
      50.times do |i|
        self.delay.fetch_grams_for_tattsta(tag, tag.partner_id)
      end
    end    
  end

  def fetch_grams(tag, cpartner_id)
    tatsagram = IInstagram.new(:token => self.token, :tag => tag.name, :max_id => tag.max_photo_id, :partner_id => cpartner_id, :client_key => AppConfiguration['cakesta']['instagram_client_id'])
    tatsagram.get_grams
  end

  def fetch_grams_for_tattsta(tag, cpartner_id)
    tatsagram = IInstagram.new(:token => self.token, :tag => tag.name, :max_id => tag.max_photo_id, :partner_id => cpartner_id, :client_key => AppConfiguration['tattsta']['instagram_client_id'])
    tatsagram.get_grams    
  end

  def likes?(photo)
    self.favorites.find_by_iphoto_id(photo.id)
  end

  def image_url
    self.image? ? self.image : "fallback/thumb_default.png"
  end
end

apistagram/app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  layout 'admin'

  before_filter :authenticate_user!, :authenticate_admin_user

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])

    respond_to do |format|
      format.html { redirect_to admin_users_url }
      format.js
    end
  end

  def fetch_photos
    if current_user.get_grams
      redirect_to admin_users_url, :notice => "Photo fetcher added to the queue. Photos will be processed and added to the system soon!"
    end
  end
end

apistagram/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :find_user, :only => :destroy
  before_filter :find_user_or_username, :except => [:destroy, :contact, :advertize, :report, :legal]
  before_filter :set_title, :except => :legal

  def show
    username = @user.class.to_s == 'User' ? @user.name : @user
    if ["likes", "commented"].include?(params[:sort]) and @user.class.to_s == 'User'
      if params[:sort] == "likes"
        @iphotos = @user.favorite_photos.by_partner_id(partner.id).paginate(:page => params[:page], :per_page => 8)
      else
        @iphotos = @user.commented_photos.by_partner_id(partner.id).paginate(:page => params[:page], :per_page => 8)
      end
    else
      @iphotos = Iphoto.by_partner_id(partner.id).listed.by_username(username).paginate(:page => params[:page], :per_page => 8)
    end
  end

  # payal says: commented the other actions as currently only view profile action is required.
  # def index
  #   @users = User.all
  # end

  # def edit
  #   @user = User.find(params[:id])
  # end

  # def update
  #   @user = User.find(params[:id])

  #   if @user.update_attributes(params[:user])
  #     redirect_to @user, notice: 'User was successfully updated.'
  #   else
  #     render action: "edit"
  #   end
  # end

  def remove_all_photos
    if current_user and current_user.is_admin? || current_user == @user
      username = @user.class.to_s == 'User' ? @user.name : @user
      @iphotos = Iphoto.by_partner_id(partner.id).where("username = ?", username)
      @iphotos.update_all({:status => false})
      redirect_to user_url(@user), :notice => "All the photos are deleted."
    else
      redirect_to users_url, :notice => "UnAuthorized Access!!!"
    end
  end

  def destroy
    if current_user and current_user.is_admin? || current_user == @user
      @user.destroy
      redirect_to iphotos_path, :notice => "Your account is deleted successfully! We are sorry to see you go :("
    else
      redirect_to iphotos_path, :notice => "UnAuthorized Access!!!"
    end
  end

  def advertize
    unless request.post?
      render :template => 'users/advertize.html.erb', :layout => false
    else
      @contact = params[:contact]
      @errors = []
      if @contact
        ['name', 'email', 'company'].each do |field|
          @errors << "#{field.titleize} cannot be blank." if @contact[field].blank?
        end
        if @errors.empty?
          Notifier.contact(@contact, 'Advertisement').deliver
          flash[:notice] = "Details sent successfully."
          render 'success.js.erb'
        else
          render 'errors.js.erb'
        end
      end
    end
  end

  def contact
    unless request.post?
      render :template => 'users/contact.html.erb', :layout => false
    else
      @contact = params[:contact]
      @errors = []
      if @contact
        ['name', 'email'].each do |field|
          @errors << "#{field.titleize} cannot be blank." if @contact[field].blank?
        end
        if @errors.empty?
          Notifier.contact(@contact, 'Contact').deliver
          flash[:notice] = "Contact sent successfully."
          render 'success.js.erb'
        else
          render 'errors.js.erb'
        end
      end
    end
  end 

   
  def report
    unless request.post?
      @purl = params[:purl]
      @purl ||= ""
      render :template => 'users/report.html.erb', :layout => false
    else
      @contact = params[:contact]
      @errors = []
      if @contact
        ['name', 'email', 'photo_url'].each do |field|
          @errors << "#{field.titleize} cannot be blank." if @contact[field].blank?
        end
        if @errors.empty?
          Notifier.contact(@contact, 'Contact').deliver
          flash[:notice] = "Report sent successfully."
          render 'success.js.erb'
        else
          render 'errors.js.erb'
        end
      end
    end
  end 

  def legal;end

  private
    def find_user_or_username
      @user = User.where("id = ? or name = ?", params[:id], params[:id]).first
      unless @user
        @user = params[:id]
      end

      redirect_to iphotos_url unless @user      
    end

    def find_user
      @user = User.where("id = ? or name = ?", params[:id], params[:id]).first
      redirect_to iphotos_url unless @user      
    end  

    def set_title
      username = @user.class.to_s == 'User' ? @user.name : @user
      @title = "#{Thread.current[:site_configuration]['app_name'].titleize} - #{username}'s' photos ::#{Thread.current[:site_configuration]['app_name']}::"
    end  
end

apistagram/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

apistagram/app/helpers/users_helper.rb
module UsersHelper
  def guest_or_user_template(user)
    user.class.to_s == "User" ? 'users/user_info' : 'users/guest_info'
  end
end

apistagram/app/views/users/_destroy.html.erb
<%if current_user and current_user.is_admin? || @user == current_user%>
  <div class="user_menu">
    <div class="user-delete">
      <div class="user-headers">
        <div class="title">
          <b>Remove all photos</b>
        </div>
        <div class="delete">
          <%=link_to 'Remove', remove_all_photos_path(@user), :confirm => 'Are you sure you want to remove all photos associated with this user? This action cannot be undone!', :method => :delete%>
        </div>
      </div>
      <div class="user-desc">
        <p>Remove all photos from grams associated with your account.</p>
      </div>  
    </div>

    <div class="user-delete">
      <div class="user-headers">
        <div class="title">
          <b>Delete account</b>
        </div>
        <div class="delete">
          <%=link_to 'Delete', remove_user_path(@user), :confirm => 'Are you sure you want to delete your account? This action cannot be undone! We are sorry to see you going :(', :method => :delete%>
        </div>
      </div>
      <div class="user-desc">
        <p>Delete your account associated with <%=Thread.current[:site_configuration]['app_name'].titleize%>.</p>
      </div>
    </div>
  </div>
<%end%>

apistagram/app/views/users/_guest_info.html.erb
<!-- user thumbnail div -->
<div class="user-profile-thumbnail user-thumbnail">
  <div class="user-thumb">
    <%=image_tag 'medium_default.gif', :alt => "#{user}'s photo", :width => 82, :height => 82%>
  </div>
  <div class="user-container">
    <div class="username">
      <h2><%=link_to user, user_path(user)%></h2>
    </div>  
    <div class="user-content">
      <p><%=user%></p>
    </div> 
    <div class="user_links">
      <div class="ulink rss disabled">
        <%=link_to '', :title=> "Follow RSS Feed"%>
      </div>
      <div class="ulink homepage disabled">
        <%=link_to '', :title=> "Visit website"%>
      </div>
    </div>    
  </div>
</div>

<%unless @iphoto%>
  <!-- User stats -->
  <div class="user-stats">
    <div class="stat-stack">
      <div class="stack-number">
        <p>0</p>
      </div>
      <div class="stack-cat">
        <p>comments</p>
      </div>
    </div>
    <div class="stat-stack">
      <div class="stack-number">
        <p>0</p>
      </div>
      <div class="stack-cat">
        <p>likes</p>
      </div>
    </div>
    <div class="stat-stack">
      <div class="stack-number">
        <p><%=Iphoto.by_username(user).listed.count%></p>
      </div>
      <div class="stack-cat">
        <p>photos</p>
      </div>
    </div>
  </div>
<%end%>

apistagram/app/views/users/_profile.html.erb
<!-- user thumbnail div -->
<div class="user-profile-thumbnail user-thumbnail">
  <div class="user-thumb">
    <%=image_tag user.image_url, :alt => "#{user.name}'s photo", :width => 82, :height => 82%>
  </div>
  <div class="user-container">
    <div class="username">
      <h2><%=link_to user.name, user_path(user.name)%></h2>
    </div>  
    <div class="user-content">
      <p><%=user.full_name || user.name%></p>
    </div>  
    <div class="user_links">
      <div class="ulink rss">
        <%=link_to '', :title=> "Follow RSS Feed"%>
      </div>
      <div class="ulink homepage">
        <%=link_to '', (user.website ? user.website : ''), :title=> "Visit website", :target => '_blank'%>
      </div>
    </div>
  </div>
</div>

apistagram/app/views/users/_user_info.html.erb
<%=render :partial => 'users/profile', :locals => {:user => user}%>
<%unless @iphoto%>
  <!-- User stats -->
  <div class="user-stats">
    <div class="stat-stack">
      <div class="stack-number">
        <p><%=link_to user.comments.where('partner_id = ?', partner.id).count, "/users/#{user.id}/photos/commented"%></p>
      </div>
      <div class="stack-cat">
        <p>comments</p>
      </div>
    </div>
    <div class="stat-stack">
      <div class="stack-number">
        <p><%=link_to user.favorites.where('partner_id = ?', partner.id).count, "/users/#{user.id}/photos/likes"%></p>
      </div>
      <div class="stack-cat">
        <p>likes</p>
      </div>
    </div>
    <div class="stat-stack">
      <div class="stack-number">
        <p><%=link_to Iphoto.by_username(user.name).where('partner_id = ?', partner.id).listed.count, user_path(user)%></p>
      </div>
      <div class="stack-cat">
        <p>photos</p>
      </div>
    </div>
  </div>
<%end%>

<%unless user.bio.blank?%>
  <div class="user_overview">
    <div class="title">Overview</div>
    <div><%=user.bio%></div>
    <div class="website"><%=link_to user.website, user.website, :target => '_blank'%></div>
  </div>
<%end%>

apistagram/app/views/users/advertize.html.erb
<%=form_tag advertize_path, :id => "ad_form", :class => 'custom_form', :remote => true do %>
  <div class="heading">Advertise with us</div>

  <div class="field">
    <label>Name <span class="hint">(required)</span></label>
    <%= text_field :contact, :name, :class => "text" %>
  </div>

  <div class="field">
    <label>Email <span class="hint">(required)</span></label>
    <%= text_field :contact, :email, :class => "text" %>
  </div>

  <div class="field">
    <label>Company Name/URL <span class="hint">(required)</span></label>
    <%= text_field :contact, :company, :class => "text" %>
  </div>
  
  <div class="field">
    <label>Comments</label>
    <%= text_area :contact, :comments, :class => "textbox", :id => 'text-input-area', :rows => '5' %>
  </div>

  <div class="submit-button">
    <%=submit_tag 'SEND', :class => 'comment-button-style'%>
    <%=link_to 'CANCEL', '', :class => 'comment-button-style grey'%>
  </div>
<%end%> 

apistagram/app/views/users/contact.html.erb
<%=form_tag contact_path, :id => "contact_form", :class => 'custom_form', :remote => true do %>
  <div class="heading">Contact <%=Thread.current[:site_configuration]['app_name']%></div>

  <div class="field">
    <label>Name <span class="hint">(required)</span></label>
    <%= text_field :contact, :name, :class => "text" %>
  </div>

  <div class="field">
    <label>Email <span class="hint">(required)</span></label>
    <%= text_field :contact, :email, :class => "text" %>
  </div>
  
  <div class="field">
    <label>Message</label>
    <%= text_area :contact, :comments, :class => "textbox", :id => 'text-input-area', :rows => '5' %>
  </div>

  <div class="submit-button">
    <%=submit_tag 'SEND', :class => 'comment-button-style'%>
    <%=link_to 'CANCEL', '', :class => 'comment-button-style grey'%>
  </div>
<%end%>

apistagram/app/views/users/errors.js.erb
alert("<%=@errors.join('\n')%>");

apistagram/app/views/users/report.html.erb
<%=form_tag report_path, :id => "report_form", :class => 'custom_form', :remote => true do %>
  <div class="heading">Report Photo</div>

  <div class="field">
    <label>Name <span class="hint">(required)</span></label>
    <%= text_field :contact, :name, :class => "text" %>
  </div>

  <div class="field">
    <label>Email <span class="hint">(required)</span></label>
    <%= text_field :contact, :email, :class => "text" %>
  </div>

  <div class="field">
    <label>URL of photo <span class="hint">(required)</span></label>
    <%= text_field :contact, :photo_url, :class => "text", :value => @purl %>
  </div>
  
  <div class="field">
    <label>Reason for reporting</label>
    <%= text_area :contact, :reason, :class => "textbox", :id => 'text-input-area', :rows => '5' %>
  </div>

  <div class="submit-button">
    <%=submit_tag 'SEND', :class => 'comment-button-style'%>
    <%=link_to 'CANCEL', '', :class => 'comment-button-style grey'%>
  </div>
<%end%> 

apistagram/app/views/users/show.html.erb
<!-- Left side user profile div -->
<div class="user-lside">
  <%=render :partial => guest_or_user_template(@user), :locals => {:user => @user}%>
  <%=render 'destroy'%>
  <!-- Rectangle -->  
  <div class="user-square">  
    <%=render :partial => 'shared/ads', :locals => {:ad => :user_left_section}%>
  </div>
</div>

<!-- Right side user profile -->
<div class="user-rside">
  <div class="userpic-container" style="overflow:hidden;">
    <%@iphotos.each do |iphoto|%>  
      <div class="user_photo_thumb" id="photo_<%=iphoto.id%>">
        <%=render :partial => 'iphotos/iphoto', :locals => {:iphoto => iphoto}%>
      </div>
    <%end%>
  </div>

  <div style='clear:both;'><%=will_paginate(@iphotos)%></div>
  
  <div class="pagination">
  </div>
</div>

apistagram/app/views/users/success.js.erb
window.location = window.location;