apistagram/config/routes.rb
Apistagram::Application.routes.draw do
  root :to => "iphotos#index"

  resources  :auths,
             :iphotos

  resources :users, :only => [:show]             

  match '/auth/:provider/callback'  => 'auths#create'
  match '/auth/failure'             => 'auths#failure'
  match '/auth/:provider/setup'     => 'auths#setup'
  match '/signin'                   => 'auths#new',      :as => :signin
  match '/signout'                  => 'auths#destroy',  :as => :signout
  match '/contact'                  => 'users#contact'
  match '/advertize'                => 'users#advertize'
  match '/report'                   => 'users#report'

  match '/contact'                  => 'users#contact',  :as => :contact, :via => :post
  match '/advertize'                => 'users#advertize',  :as => :advertize, :via => :post
  match '/report'                   => 'users#report',  :as => :report, :via => :post

  match '/users/:id/photos/:sort'   => 'users#show'
  match '/legal'   => 'users#legal', :as => :legal

  namespace :admin do
    resources :users, :only => [:index, :destroy]
    resources :iphotos
    root :to => "users#index"


    match "fetch_photos" => 'users#fetch_photos', :as => 'fetch_photos', :via => 'post'
    match "approve_photos" => 'iphotos#approve_photos', :as => 'approve_photos', :via => 'post'
  end

  match '/remove_all_photos/:id'  => 'users#remove_all_photos', :via => :delete, :as => 'remove_all_photos'
  match '/remove_user/:id'  => 'users#destroy', :via => :delete, :as => 'remove_user'
  match "cakesta/:category"         => 'iphotos#index'
  match "cakesta/:category/:sort"   => 'iphotos#index' 
  match "tattsta/:category"         => 'iphotos#index'
  match "tattsta/:category/:sort"   => 'iphotos#index'
  match "tatstagram/:category"         => 'iphotos#index'
  match "tatstagram/:category/:sort"   => 'iphotos#index'     
  match 'iphotos/:id/favorite'    => 'iphotos#favorite', :via => 'get', :as => 'favorite'
  match 'iphotos/:id/add_comment' => 'iphotos#add_comment', :via => :post, :as => 'add_comment'
  match 'iphotos/:id/remove_comment/:comment_id' => 'iphotos#remove_comment', :via => :delete, :as => 'remove_comment'
  match 'login'                   => 'auths#new', :as => 'login' 
  match '/:id' => 'iphotos#public_show'
end

apistagram/app/models/iphoto.rb
class Iphoto < ActiveRecord::Base

  acts_as_commentable
  
  attr_accessible :i_id, :status, :tag_id, :url, :username, :partner_id

  validates :url, :username,
            :presence => true

  validates :i_id,
            :presence => true,
            :uniqueness => true

  # default_scope where(:partner_id => 2)
  belongs_to :partner
  scope :pending, where("status is null")
  scope :selected, where("status is true")
  scope :listed, where("status is null or status is true")
  scope :rejected, where("status is not null and status is false")

  self.per_page = 18

  has_many :favorites, :dependent => :destroy
  has_many :fans, :through => :favorites, :source => :user

  scope :by_username, lambda{ |username| where(username: username) unless username.nil? }
  scope :by_partner_id, lambda{ |partner_id| where(partner_id: partner_id) unless partner_id.nil? }

  before_save :create_or_update_public_id

  def create_or_update_public_id
    unless public_id
      pub_id = SecureRandom.hex(3)
      if check_public_id(pub_id)
        pub_id = SecureRandom.hex(3)
        check_public_id(pub_id)
      else
        self.public_id = pub_id
      end
    end
  end

  def check_public_id(pub_id)
    Iphoto.find_by_public_id(pub_id)
  end

  def share_link
    Thread.current[:site_configuration]['host'] + "/#{public_id}"
  end

  def self.update_all_with_callbacks(photo_ids, all_photo_ids)
    photo_ids     ||= []
    all_photo_ids = all_photo_ids.split(" ")
    
    approved_count = 0
    removed_count  = 0

    all_photo_ids.each do |pic|
      photo = self.find_by_id(pic.to_i)
        
      if photo
        if photo_ids.include?(pic)
          removed_count = removed_count + 1 if photo.update_attribute(:status, false)
        else
          approved_count = approved_count + 1 if photo.update_attribute(:status, true)
        end
      end
    end
    
    [approved_count, removed_count]
  end

  def user
    User.find_by_name(username)
  end

  def self.get_duration(sort_order)
    if sort_order == "month"
      return 1.month.ago(Time.now)
    elsif sort_order == "week"
      return 1.week.ago(Time.now)
    else
      return 1.day.ago(Time.now)
    end
  end

  def self.get_hottest_pics(dtime, counter = 1)
    # debugger
    if self.count == 0
      return []
    else
      duration = Thread.current[:site_configuration]['hot_duration_in_hours'] * counter
      time = duration.hours.ago(dtime)

      arr = self.joins(:favorites).where('iphotos.id = favorites.iphoto_id')
      if arr.count < 9
        return arr
      else
        arr = self.joins(:favorites).where('favorites.created_at >= ? and iphotos.id = favorites.iphoto_id', time).limit(9)
        if !arr || arr.count < 9
          counter = counter + 1
          get_hottest_pics(time, counter)
        else
          arr
        end
      end
    end
  end

  def self.fetch_index_listing(cpartner_id, category = nil, sort_order = nil)   
    hot_arr = Iphoto.by_partner_id(cpartner_id).get_hottest_pics(Time.now)
    pop_arr = Iphoto.joins(:favorites).where('iphotos.partner_id = ? and favorites.created_at >= ? and iphotos.id = favorites.iphoto_id', cpartner_id, Thread.current[:site_configuration]['popular_duration_in_days'].day.ago(Date.today))

    if category
      if category == "hot"
        if hot_arr.empty?
          return []
        else
          return hot_arr.group(:iphoto_id).order('count(favorites.id) desc')
        end
      elsif category == "most_popular"
        if sort_order and ["month", "week", "today"].include?(sort_order)
          return pop_arr.where('favorites.created_at >= ?', get_duration(sort_order)).group(:iphoto_id).order('count(favorites.id) desc')
        else
          return pop_arr.group(:iphoto_id).order('count(favorites.id) desc')
        end        
      else
        return self.by_partner_id(cpartner_id).order('created_at desc')
      end
    else
      newest  = self.by_partner_id(cpartner_id).order('created_at desc').limit(6)

      hottest = hot_arr.empty? ? [] : hot_arr.group(:iphoto_id).order('count(favorites.id) desc')

      popular = pop_arr.empty? ? [] : pop_arr.group(:iphoto_id).order('count(favorites.id) desc').limit(6)
      return [newest, hottest, popular]
    end
  end
end

apistagram/app/controllers/admin/iphotos_controller.rb
class Admin::IphotosController < ApplicationController
  layout 'admin'

  before_filter :authenticate_user!, :authenticate_admin_user

  def index
    @iphotos = Iphoto.page(params[:page]).pending
  end
  
  def approve_photos
    @prev_count     = Iphoto.selected.count
    result          = Iphoto.update_all_with_callbacks(params[:iphoto_ids], params["all_photo_ids"])
    @new_count      = Iphoto.selected.count

    removed_count = result[1]
    approved_count = result[0]
    
    redirect_to admin_iphotos_path, :notice => "#{approved_count} photos approved and #{removed_count} removed."
  end
end

apistagram/app/controllers/iphotos_controller.rb
require 'will_paginate/array'
class IphotosController < ApplicationController

  def index
    if params[:category]
      @category = params[:category]
      @sort     = params[:sort]
      @iphotos  = Iphoto.fetch_index_listing(partner.id, params[:category], params[:sort]).paginate(:page => params[:page], :per_page => 21)
      @title    = Thread.current[:site_configuration]['title'][@category]
    else
      @newest, @hottest, @popular = Iphoto.fetch_index_listing(partner.id)
    end
  end

  def public_show
    @iphoto = Iphoto.by_partner_id(partner.id).listed.where("public_id = ?", params[:id]).first
    if @iphoto
      @recent_photos = Iphoto.by_partner_id(partner.id).listed.where("username = ? and id != ?", @iphoto.username, @iphoto.id).limit(6)
      render :template => 'iphotos/show'
    else
      redirect_to iphotos_url
    end
  end

  def show
    @iphoto = Iphoto.by_partner_id(partner.id).listed.where("id = ?", params[:id]).first
    if @iphoto
      @recent_photos = Iphoto.by_partner_id(partner.id).listed.where("username = ? and id != ?", @iphoto.username, @iphoto.id).limit(6)
    else
      redirect_to iphotos_url
    end
  end

  def destroy
    @iphoto = Iphoto.by_partner_id(partner.id).where(:id => params[:id]).first
    if current_user and current_user.is_admin? || current_user.name == @iphoto.username 
      #@iphoto.destroy 
      @iphoto.update_attribute(:status, false)
      redirect_to iphotos_url, :notice => "Photo removed successfully!"
    else
      redirect_to iphoto_url, :notice =>  "You do not have access to this photo edit permissions."
    end
  end

  def favorite
    @size = params[:size]
    @iphoto = Iphoto.by_partner_id(partner.id).where(:id => params[:id]).first
    favorite = @iphoto.favorites.find_by_user_id(current_user.id)

    if favorite 
      favorite.destroy
    else
      @iphoto.favorites.create(:user_id => current_user.id, :partner_id => @iphoto.partner_id)
    end

    respond_to do |format|
      format.html { redirect_to iphoto_url(@iphoto) }
      format.json { head :no_content }
      format.js {}
    end
  end

  def add_comment
    @iphoto = Iphoto.by_partner_id(partner.id).where(:id => params[:id]).first
    @user_who_commented = current_user
    if current_user 
      @comment = Comment.build_from( @iphoto, @user_who_commented.id, params[:comment])
      @comment.partner_id = @iphoto.partner_id
      if @comment.save
        return render 'add_comment.js.erb'
      else
        return render :nothing => true
      end
    else
      redirect_to login_url
    end
  end

  def remove_comment
    @iphoto = Iphoto.by_partner_id(partner.id).where(:id => params[:id]).first
    @comment = @iphoto.comment_threads.find_by_id(params[:comment_id])
    if @comment and current_user.name == @iphoto.username || current_user == @comment.user
      @comment.destroy
      return render 'remove_comment.js.erb'
    else
      return render :nothing => true
    end
  end
end

apistagram/app/helpers/admin/iphotos_helper.rb
module Admin::IphotosHelper
end

apistagram/app/helpers/iphotos_helper.rb
module IphotosHelper
end

apistagram/app/views/iphotos/_comment.html.erb
<!-- START OF ACTUAL COMMENT -->
<div class="acomment" id="comment_<%=comment.id%>">
  <div class="user-thumb">
    <%=image_tag comment.user.image_url, :alt => "#{comment.user.name}'s thumb", :width => 82, :height => 82%>
  </div>
  <div class="comment-container">
    <div class="comment-username">
      <h2><%=link_to comment.user.name, user_url(comment.user)%></h2>
    </div>
    <div class="comment-body">
      <%=raw comment.body%>
    </div>
    <div class="comment-date">
      <p><%="#{time_ago_in_words(comment.created_at)} ago"%></p>
    </div>
    <%if current_user and (current_user.name == @iphoto.username || current_user == comment.user)%>
      <div class="delete-comment">
        <%=remove_comment(@iphoto, comment)%>
      </div>
    <%end%>
  </div>
</div>

apistagram/app/views/iphotos/_comment_form.html.erb
<%= tinymce_assets %>
<%if current_user %>
  <!-- Leave a comment section - Logged in  -->
  <%=form_tag add_comment_path(@iphoto), :id => "add_comment", 'data-remote' => true do %>
    <div class="leavecomment">
      <div class="leave-title">
        <h2>Leave a comment</h2>
      </div>
      <div class="text-area">
        <%= text_area_tag :comment, "", :class => "tinymce textbox", :id => 'text-input-area' %>
        <%= tinymce %>
      </div>
      <div class="submit-button">
        <%=submit_tag 'POST COMMENT', :class => 'comment-button-style'%>
      </div>
    </div>
  <%end%>  
<%else%> 
  <div class="leavecomment">
    <div class="submit-button"><%=link_to 'LOG IN TO POST COMMENT', login_url, :class => 'comment-button-style'%></div>
  </div>
<%end%>

apistagram/app/views/iphotos/_form.html.erb
<%= form_for(@iphoto) do |f| %>
  <% if @iphoto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@iphoto.errors.count, "error") %> prohibited this iphoto from being saved:</h2>

      <ul>
      <% @iphoto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :i_id %><br />
    <%= f.text_field :i_id %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br />
    <%= f.number_field :tag_id %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

apistagram/app/views/iphotos/_iphoto.html.erb
<div class="thumb">
  <div class="thumb-off">
    <a href="single.html" class="outerLink"><%=image_tag iphoto.url, :alt => "", :width => 286, :height => 239, :class=>'iImg'%></a>
  </div>
  <div class="thumb-hover">
  </div>
  
  <div class="call-text">
    <%=link_to (content_tag(:span, 'Click here to see full size')), iphoto.share_link%>
  </div>
</div>
<%=render :partial => 'iphotos/stats', :locals => {:iphoto => iphoto, :user => current_user}%>

apistagram/app/views/iphotos/_recent.html.erb
<!-- Div for title of photos -->
<div class="photo_line_title">
  <h1>What's Hot</h1>
</div>
<div class="photo_line">
  <%@hottest.each_with_index do |iphoto, i|%>
    <!-- Individual photo div -->
    <div class="photoHolder photo_thumb photo_<%=iphoto.id%>">
      <%=render :partial => 'iphoto', :locals => {:iphoto => iphoto}%>
    </div>
<!--     <%#- if (i+1)%3 == 0%>
      <div class="clear"></div>
    <%#end%> -->     
  <%end%>
</div>

<div class="more">
  <%=link_to "More What's Hot →",  "/#{Thread.current[:site_configuration]['app_name']}/hot"%>
</div>
<div class="ad">
  <%=render :partial => 'shared/ads', :locals => {:ad => :whats_hot_section}%>
</div>

<!-- Div for title of photos -->
<div class="photo_line_title">
  <h1>Most Popular</h1>
</div>
<div class="photo_line">
  <%@popular.each_with_index do |iphoto, i|%>
    <!-- Individual photo div -->
    <div class="photoHolder photo_thumb photo_<%=iphoto.id%>">
      <%=render :partial => 'iphoto', :locals => {:iphoto => iphoto}%>
    </div>
<!--     <%#- if (i+1)%3 == 0%>
      <div class="clear"></div>
    <%#end%> -->      
  <%end%>
</div>

<div class="more">
  <%=link_to "More Most Popular →",  "/#{Thread.current[:site_configuration]['app_name']}/most_popular"%>
</div>
<div class="ad">
  <%=render :partial => 'shared/ads', :locals => {:ad => :popular_section}%>
</div>

<!-- Div for title of photos -->
<div class="photo_line_title">
  <h1>Newest</h1>
</div>
<div class="photo_line">
  <%@newest.each_with_index do |iphoto, i|%>
    <!-- Individual photo div -->
    <div class="photoHolder photo_thumb photo_<%=iphoto.id%>">
      <%=render :partial => 'iphoto', :locals => {:iphoto => iphoto}%>
    </div>
<!--     <%#- if (i+1)%3 == 0%>
      <div class="clear"></div>
    <%#end%>  -->   
  <%end%>
</div>
<div class="more">
  <%=link_to "More Newest →", "/#{Thread.current[:site_configuration]['app_name']}/newest"%>
</div>

apistagram/app/views/iphotos/_stats.html.erb
<div class="thumb_stats">
  <div class="comment-stat">
    <%=comment_link(iphoto, user)%>
  </div>
  <div class="like-stat">
    <%=heart_link(iphoto, user)%>
  </div> 
</div>
<div class="photo_username">
  <%=link_to content_tag(:h3, iphoto.username), user_path(iphoto.username), :title => "View #{iphoto.username}'s profile"%>
</div>

apistagram/app/views/iphotos/add_comment.js.erb
$('#comment_list').append("<%=escape_javascript(render :partial => 'comment', :locals => {:comment => @comment})%>")
$('#text-input-area').val('');
$('.number-comments h2').html("<%=@iphoto.comment_threads.count%> Comments");
tinyMCE.activeEditor.setContent('');

apistagram/app/views/iphotos/edit.html.erb
<h1>Editing iphoto</h1>

<%= render 'form' %>

<%= link_to 'Show', @iphoto %> |
<%= link_to 'Back', iphotos_path %>

apistagram/app/views/iphotos/favorite.js.erb
if("<%=@size%>" == "large") {
  $('.imagelike').html('<%=heart_link(@iphoto, current_user, :large)%>');
}
else {
  $('.photo_<%=@iphoto.id%>').html("<%=escape_javascript(render :partial => 'iphoto', :locals => {:iphoto => @iphoto})%>");
  $('#photo_<%=@iphoto.id%>').html("<%=escape_javascript(render :partial => 'iphoto', :locals => {:iphoto => @iphoto})%>");
}

apistagram/app/views/iphotos/index.html.erb
<%-if @category%>
  <%if @category == "most_popular"%>
    <div class="photo_line_title_pop">
      <h1><%= Thread.current[:site_configuration][@category] %></h1>
    </div>
    <div class="sub-nav">
      <p>
        <a href="/<%=Thread.current[:site_configuration]['app_name']%>/most_popular/all"><span class="<%=@sort == 'all' ? 'active' : ''%>">All Time</span></a> | 
        <a href="/<%=Thread.current[:site_configuration]['app_name']%>/most_popular/month"><span class="<%=@sort == 'month' ? 'active' : ''%>">This Month</span></a> | 
        <a href="/<%=Thread.current[:site_configuration]['app_name']%>/most_popular/week"><span class="<%=@sort == 'week' ? 'active' : ''%>">This Week</span></a> | 
        <a href="/<%=Thread.current[:site_configuration]['app_name']%>/most_popular/today"><span class="<%=@sort == 'today' ? 'active' : ''%>">Today</span></a>
      </p>
    </div>
  <%else%>
    <div class="photo_line_title">
      <h1><%= Thread.current[:site_configuration][@category] %></h1>
    </div>
  <%end%>
  <div class="photo_line">
    <%@iphotos.each_with_index do |iphoto, i|%>
      <!-- Individual photo div -->
      <div class="photoHolder photo_thumb photo_<%=iphoto.id%>">
        <%=render :partial => 'iphoto', :locals => {:iphoto => iphoto}%>
      </div>
<!--       <%#- if (i+1)%3 == 0%>
        <div class="clear"></div>
      <%#end%> -->
      <%- if i == 8%>
        <div class="clear"></div>
        <div class="ad">
          <%=render :partial => 'shared/ads', :locals => {:ad => :whats_hot_section}%>
        </div>
      <%end%>  
      <%- if i == 14%>
        <div class="clear"></div>
        <div class="ad">
          <%=render :partial => 'shared/ads', :locals => {:ad => :popular_section}%>
        </div>
      <%end%>
    <%end%>
  </div>
  <%=will_paginate(@iphotos)%>
<%else%>
  <%=render 'recent'%>
<%end%>

apistagram/app/views/iphotos/new.html.erb
<h1>New iphoto</h1>

<%= render 'form' %>

<%= link_to 'Back', iphotos_path %>

apistagram/app/views/iphotos/remove_comment.js.erb
$('#comment_<%=@comment.id%>').remove();
$('.number-comments h2').html("<%=@iphoto.comment_threads.count%> Comments");

apistagram/app/views/iphotos/show.html.erb
<div class="single_line_title">
  <h1>
    <%=link_to "#{@iphoto.username}'s", user_path(@iphoto.username)%> photo
  </h1>
</div>

<!-- left side of single image page -->

<div class="l-side-single">
  <!-- large image div -->
  <div class="large-image">
    <%= image_tag @iphoto.url, :alt => "#{@iphoto.username}'s photo", :width=> 518 %>
    <!-- image sharing -->      
    <div id="i_social">
      <a href="https://twitter.com/share" class="twitter-share-button" data-via="<%=Thread.current[:site_configuration]['social']['tw']%>" data-count="none">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
	<div id="pinterest">
      <a style="margin-top: -15px !important;" href="http://pinterest.com/pin/create/button/?url=<%=url_for(@iphoto.share_link)%>&media=<%=url_for(@iphoto.url)%>&description=<%=Thread.current[:site_configuration]['app_name']%>" class="pin-it-button" count-layout="none"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It" /></a>
    </div>
      <g:plusone size="medium" annotation="none"></g:plusone>
      <div class="fb-like" data-href="<%=url_for('http://www.facebook.com/sharer.php?u=' + @iphoto.share_link + '&amp;t=' + Thread.current[:site_configuration]['app_name'])%>" data-send="false" data-layout="button_count" data-width="150" data-show-faces="false" data-font="arial" data-rel="<%=url_for(@iphoto.url)%>"></div>
    </div> 
    <!-- Like image -->
    <div class="imagelike">
      <%=heart_link(@iphoto, current_user, :large)%>
    </div>
  </div>
  <!-- banner -->
  <div class="single-banner">
    <%=render :partial => 'shared/ads', :locals => {:ad => :iphoto_left_section}%>
  </div>

  <!-- Comments section -->
  <div class="comments" id="all_comments">
    <div class="comments-header">
      <div class="number-comments">
        <h2><%=@iphoto.comment_threads.count%> Comments</h2>
      </div>
      <div class="leave-comment-top">
        <a href="#add_comment"><p>leave a comment</p></a>
      </div>  
    </div>
    <div id="comment_list">
      <%@iphoto.comment_threads.each do |comment|%>
        <%=render :partial => 'comment', :locals => {:comment => comment}%>
      <%end%> 
    </div>
    <%=render 'comment_form'%>
  </div>
</div>

<!-- right side of single image page -->

<div class="r-side-single">

  <!-- user thumbnail div -->
  <%=render :partial => user_profile_link(@iphoto.user), :locals => {:user => (@iphoto.user ? @iphoto.user : @iphoto.username)}%>

  <!-- stats div -->
  <div class="image-stats">
    <div class="stat">
      <%=image_tag 'single-heart.gif', :class => 'imgmiddle'%>
      <span class="vert-header"><%=@iphoto.fans.count%> likes</span>
    </div>
    <div class="stat">
      <%=image_tag 'single-comment.gif', :class => 'imgmiddle'%>
      <span class="vert-header"><%=@iphoto.comment_threads.count%> comments</span>
    </div>  
    <div class="stat" id="custom-tweet-button">
      <a class="imgmiddle meta-act-link meta-tweet" href="http://twitter.com/intent/tweet?text=<%= url_for(@iphoto.share_link) %>">  
        <%=image_tag 'single-twitter.gif', :class => 'imgmiddle'%>       
        <span class="vert-header">Tweet this</span>
      </a>
    </div>
    <div class="stat">
      <%
        fb_share_link = url_for('http://www.facebook.com/sharer.php?u=' + @iphoto.share_link + '&amp;t=' + Thread.current[:site_configuration]['app_name'])
      %>
      <a onclick="window.open('<%=fb_share_link%>','linkname','height=320, width=600,scrollbars=no')" href="javascript:void(0)">
        <%=image_tag 'single-facebook.gif', :class => 'imgmiddle'%>
        <span class="vert-header">Share on Facebook</span>
      </a>
    </div>
    <div class="stat">
      <%=image_tag 'single-link.gif', :class => 'imgmiddle'%>
      <span class="vert-header">
        <%=text_field_tag :public_link, @iphoto.share_link, :class => "displayLink"%>
      </span>
    </div>
    <div class="stat">
      <a href="/report?purl=<%=url_for(@iphoto.share_link)%>" class='fancybox'><%=image_tag 'single-report.gif', :class => 'imgmiddle'%>
      <span class="vert-header">Report Photo</span></a>
    </div>
    <%if logged_in? and (current_user.is_admin? || current_user.name == @iphoto.username)%>
      <div class="stat">
        <%=link_to image_tag('single-delete.gif', :class => 'imgmiddle') + content_tag(:span, 'Delete Photo', :class=>"vert-header"), iphoto_url(@iphoto), :method => :delete, :confirm => "Are you sure? This action cannot be undone!" %>
      </div>
    <%end%>
  </div> 
  <!-- more from user -->
  <div class="more-from-user">
    <div class="more-user-title">
      <h2>More from this user</h2>
    </div>
    <%@recent_photos.each do |pic|%>
      <div class="more-thumb">
        <%=link_to image_tag(pic.url, :width => 110, :height => 110, :alt => '', :class => 'iImg'), iphoto_url(pic)%>
      </div>
    <%end%>
  </div>
  <!-- 336x280 -->
  <div class="large-rec">
    <%=render :partial => 'shared/ads', :locals => {:ad => :iphoto_right_section}%>
  </div>
</div>