apistagram/config/routes.rb
Apistagram::Application.routes.draw do
  root :to => "iphotos#index"

  resources  :auths,
             :iphotos

  resources :users, :only => [:show]             

  match '/auth/:provider/callback'  => 'auths#create'
  match '/auth/failure'             => 'auths#failure'
  match '/auth/:provider/setup'     => 'auths#setup'
  match '/signin'                   => 'auths#new',      :as => :signin
  match '/signout'                  => 'auths#destroy',  :as => :signout
  match '/contact'                  => 'users#contact'
  match '/advertize'                => 'users#advertize'
  match '/report'                   => 'users#report'

  match '/contact'                  => 'users#contact',  :as => :contact, :via => :post
  match '/advertize'                => 'users#advertize',  :as => :advertize, :via => :post
  match '/report'                   => 'users#report',  :as => :report, :via => :post

  match '/users/:id/photos/:sort'   => 'users#show'
  match '/legal'   => 'users#legal', :as => :legal

  namespace :admin do
    resources :users, :only => [:index, :destroy]
    resources :iphotos
    root :to => "users#index"


    match "fetch_photos" => 'users#fetch_photos', :as => 'fetch_photos', :via => 'post'
    match "approve_photos" => 'iphotos#approve_photos', :as => 'approve_photos', :via => 'post'
  end

  match '/remove_all_photos/:id'  => 'users#remove_all_photos', :via => :delete, :as => 'remove_all_photos'
  match '/remove_user/:id'  => 'users#destroy', :via => :delete, :as => 'remove_user'
  match "cakesta/:category"         => 'iphotos#index'
  match "cakesta/:category/:sort"   => 'iphotos#index' 
  match "tattsta/:category"         => 'iphotos#index'
  match "tattsta/:category/:sort"   => 'iphotos#index'
  match "tatstagram/:category"         => 'iphotos#index'
  match "tatstagram/:category/:sort"   => 'iphotos#index'     
  match 'iphotos/:id/favorite'    => 'iphotos#favorite', :via => 'get', :as => 'favorite'
  match 'iphotos/:id/add_comment' => 'iphotos#add_comment', :via => :post, :as => 'add_comment'
  match 'iphotos/:id/remove_comment/:comment_id' => 'iphotos#remove_comment', :via => :delete, :as => 'remove_comment'
  match 'login'                   => 'auths#new', :as => 'login' 
  match '/:id' => 'iphotos#public_show'
end

apistagram/app/views/layouts/_footer.html.erb
<!-- Footer wrapper div -->

<div id="footer_wrapper">
  <!-- Footer div -->
  <div id="footer">
    <!-- Footer links section -->
    <div id="f_links">
      <%=image_tag 'balls.png', :alt => "balls", :class=>"balls"%>
      <h1>Important Links</h1>
      <ul>
        <a href="/contact" class='fancybox'><li>Contact Us</li></a>
        <a href="/advertize" class='fancybox'><li>Advertise</li></a>
        <a href="/legal"><li>Legal Stuff</li></a>
        <a href="/report" class='fancybox'><li>Report an Image</li></a>
        <li class="legal">© 2012 <a href="#">Vagabond Digital</a></li>
      </ul>
    </div>

    <!-- Footer social section -->
    <div id="f_social">
      <%=image_tag 'balls.png', :alt => "balls", :class=>"balls"%>
      <h1>Connect with us</h1>
      <ul>
        <li>
          <a href="https://twitter.com/<%=Thread.current[:site_configuration]['social']['tw']%>">
            <%=image_tag 'twitter-icon.png', :alt=>"twitter-icon", :width=>"24", :height=>"24", :class=>"imgmiddle"%> Twitter
          </a>
        </li>
        <li>
          <a href="https://www.facebook.com/<%=Thread.current[:site_configuration]['social']['fb']%>">
            <%=image_tag 'facebook-icon.png', :alt=>"twitter-icon", :width=>"24", :height=>"24", :class=>"imgmiddle"%> Facebook
          </a>
        </li>
        <li>
          <a href="http://pinterest.com/<%=Thread.current[:site_configuration]['social']['pin']%>">
            <%=image_tag 'pinterest-icon.png', :alt=>"twitter-icon", :width=>"24", :height=>"24", :class=>"imgmiddle"%> Pinterest
          </a>
        </li>
<!--         <li>
          <a href="#">
            <%#=image_tag 'mobile-icon.png', :alt=>"twitter-icon", :width=>"24", :height=>"24", :class=>"imgmiddle"%>Mobile
          </a>
        </li> -->
      </ul>
    </div>
    
    <!-- Footer network section -->
    <div id="f_network">
      <%=image_tag 'balls.png', :alt => "balls", :class=>"balls"%>    
      <h1>Our Network</h1>
      <ul>
        <a href="http://tattsta.com"><li>Tattsta.com - Share your tattoos</li></a>
        <a href="http://cakesta.com"><li>Cakesta.com - Share your cakes</li></a>
       <!--  <a href="#"><li>Tattogram - Share your tattoos</li></a>
        <a href="#"><li>Tattogram - Share your tattoos</li></a> -->
      </ul>
    </div>

    <!-- Footer sign up w/Instagram -->    
    <div id="f_signup"> 
      <%=image_tag 'balls.png', :alt => "balls", :class=>"balls"%>
      <h1>Want to create an account?</h1>
      <p>All of our photos are collected from users of the photo sharing service Instagram. If you want to get in on the action, including commenting and liking these photos, <%=link_to "create an account", "http://help.instagram.com/customer/portal/articles/95719", :target => '_blank'%> to get started.</p>
      <p class="apiblurb">This product uses the Instagram API but is not endorsed or certified by Instagram.</p>
    </div>
    
    <!-- Close footer div -->       
  </div>
</div>

<!-- Share button scripts -->
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=141939898390";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<script type="text/javascript">
  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/plusone.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script>
<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>

<script type="text/javascript">
  $(document).ready(function() {
    $("a.fancybox").fancybox();
  });
</script>

apistagram/app/views/layouts/_header.html.erb
<!-- Header Wrapper -->
<div id="header_wrapper">
	<!-- Header -->
	<div id="header">
		<!-- Logo div -->
		<div id="h_logo">
		  <%= link_to image_tag("#{Thread.current[:site_configuration]['app_name']}.png", :alt => "#{Thread.current[:site_configuration]['app_name']} - Share your Instagram photos"), root_url%>
		</div>

		<!-- Header banner ad div -->
		<div id="h_banner">
      <%=render :partial => 'shared/ads', :locals => {:ad => :header}%>
		</div>   

    <%- if logged_in? %>
      <div id="logged_in">
        <div class="loggedin-user-thumb">
          <%=image_tag current_user.image_url, :alt => current_user.name, :width=>"45", :height=>"45"%>
        </div>
        <div class="loggedin-username">  
          <a href="#"> <p><%=current_user.name%></p> </a>  
          <p class="user-control"><%=link_to "sign out", signout_path%> | <%=link_to 'view profile', user_path(current_user)%></p>
        </div>
      </div>
    <%else%>
      <div id="h_signin">
        <%= link_to '', new_auth_path, :class => 'sign_in_btn'%>
        <span class="register">or <%=link_to "register", 'http://help.instagram.com/customer/portal/articles/95719', :target => '_blank'%> for an account</span>
      </div>
    <%end%>

	<!-- Close header div -->
	</div>	
<!-- Close Header Wrapper Div -->
</div>

apistagram/app/views/layouts/_nav.html.erb
<!-- Nav wrapper div -->

<div id="nav_wrapper">
  <!-- Main nav div -->
  <div id="nav">
    <!-- Left side of nav div -->
    <div id="l_nav">
      <p>
        <%=link_to "What's Hot",    "/#{Thread.current[:site_configuration]['app_name']}/hot", :class => "#{@category == 'hot' ? 'active' : ''}"%> | 
        <%=link_to "Most Popular",  "/#{Thread.current[:site_configuration]['app_name']}/most_popular", :class => "#{@category == 'most_popular' ? 'active' : ''}"%> | 
        <%=link_to "Newest",        "/#{Thread.current[:site_configuration]['app_name']}/newest", :class => "#{@category == 'newest' ? 'active' : ''}"%>
      </p>
    </div>
    
    <!-- Right side of nav div -->
    <div id="r_nav">
      <p>Tag <span class="bold-pink">#<%=Thread.current[:site_configuration]['app_name']%></span> on your <span class="bold">Instagram</span> photos to appear on the site!!!</p>
    </div>
  <!-- Close nav div -->
  </div>
<!-- Close nav wrapper div -->  
</div>  

apistagram/app/views/layouts/_social.html.erb
<!-- Social Menu Container -->
<div id="social-nav">
  <!-- Social Follows -->
  <div class="social-follow">
    <div class="social-title">
      <p style="text-transform:uppercase;">FOLLOW <%=Thread.current[:site_configuration]['app_name']%></p>
    </div>
    <div class="social-follow-holder">
      <div class="follow-button1">
        <a href="https://twitter.com/<%=Thread.current[:site_configuration]['social']['tw']%>"  target='_blank'>
        </a>
      </div>
      
      <div class="vr">
        <%=image_tag 'vr.gif', :alt=>"vr", :width=>"2", :height=>"24"%>
      </div>
      
      <div class="follow-button2">
        <a href="https://www.facebook.com/<%=Thread.current[:site_configuration]['social']['fb']%>" target='_blank'> 
        </a>
      </div>
      
      <div class="vr">
        <%=image_tag 'vr.gif', :alt=>"vr", :width=>"2", :height=>"24"%>
      </div>
      
      <div class="follow-button3">
        <a href="http://pinterest.com/<%=Thread.current[:site_configuration]['social']['pin']%>" target='_blank'> 
        </a>
      </div>
    
    </div>
  
  </div>
  
  <!-- Social Share --> 
  
  <div class="social-share">
  
    <div class="social-title">
    
      <p style="text-transform:uppercase;">SHARE <%=Thread.current[:site_configuration]['app_name']%></p>
    
    </div>
    
    <div class="social-share-holder">
      
      <a href="https://twitter.com/share" class="twitter-share-button" data-via="<%=Thread.current[:site_configuration]['app_name']%>" data-count="none">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

	<div id="pinterest">

    	<a style="margin-top: -15px !important;" href="http://pinterest.com/pin/create/button/?url=http%3A%2F%2F<%=Thread.current[:site_configuration]['app_name']%>.com&media=http%3A%2F%2F<%=Thread.current[:site_configuration]['app_name']%>.com%2Fassets%2Flogo-6bdef5a8d30bcde62f4af1b0baad945f.png&description=<%=Thread.current[:site_configuration]['app_name']%>" class="pin-it-button" count-layout="none"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It" /></a>
    
    </div>


    <g:plusone size="medium" annotation="none"></g:plusone>

    <div class="fb-like" data-href="http://www.<%=Thread.current[:site_configuration]['app_name']%>.com/#" data-send="false" data-layout="button_count" data-width="50" data-show-faces="false" data-font="arial"></div>
    </div>
  
  
  </div>

</div>    

apistagram/app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Apistagram" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "admin/application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Apistagram</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Users", admin_users_path  %></li>
              <li><%= link_to "Photos", admin_iphotos_path  %></li>
              <%= link_to "Fetch New Photos", admin_fetch_photos_path, :class=> "btn btn-primary btn-primary", :method => :post %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span12 notice">
            <%= flash[:notice] %>
          </div>
        </div>
        <div class="row">
          <div class="content">
            <%= yield %>
          </div>
<!--           <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%#= link_to "Link1", "/path1"  %></li>
                <li><%#= link_to "Link2", "/path2"  %></li>
                <li><%#= link_to "Link3", "/path3"  %></li>
              </ul>
            </div>
          </div><-->
        </div>
      </div>
      <footer>
        <p>&copy;<%= Thread.current[:site_configuration]["copyright_text"] %></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <script>
      <%= yield :javascript_bottom %>
    </script>
  </body>
</html>

apistagram/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns:fb="https://www.facebook.com/2008/fbml">
  <head>
    <meta name="description" content="<%=Thread.current[:site_configuration]['meta_tags']%>">
    <title><%=@title || Thread.current[:site_configuration]['title']['default']%></title>
    <%= stylesheet_link_tag "style", :media => "all" %>
    <%=javascript_include_tag 'application'%>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%=render 'layouts/header'%>
    <%=render 'layouts/nav'%>
    <div id="container">
      <%=render 'layouts/social'%>
      <div id='notice'>
        <%if flash[:notice]%>
          <div class='notice'><%=flash[:notice]%></div>
        <%end%>
      </div>
      <%= yield %>
    </div>
    <%=render 'layouts/footer'%>

    <script>
      $.fn.broken = function(){
        return this.each(function(){
          if(!this.complete || (typeof this.naturalWidth != 'undefined' && this.naturalWidth == 0)) {
            $(this).attr("src", '/assets/fallback/content_removed.gif');
            $(this).parents('.thumb:first').find('.call-text').remove();
            $(this).parents('.more-thumb').hide(); 
          }
        });
      };

      $(window).load(function () {
        $('.iImg').broken();
      });
    </script>
    <%if partner.name == 'cakesta'%>
      <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-35768230-2']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
      </script> 
    <%else%>   
      <script type="text/javascript">

        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-35768230-3']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

      </script>
    <%end%>
  </body>
</html>